add_lunch_combo simpleaosp_flo-user
add_lunch_combo simpleaosp_flounder-user
add_lunch_combo simpleaosp_hammerhead-user
add_lunch_combo simpleaosp_mako-user
add_lunch_combo simpleaosp_manta-user
add_lunch_combo simpleaosp_shamu-user
